import { GraphQLUnionType } from "graphql";
import ActivityNotificationAirdropCompletedGqlType from "src/schema/object/notifications/ActivityNotificationAirdropCompletedGqlType";
import ActivityNotificationAirdropGiftReceivedGqlType from "src/schema/object/notifications/ActivityNotificationAirdropGiftReceivedGqlType";
import ActivityNotificationBidderAuctionAlmostOverGqlType from "src/schema/object/notifications/ActivityNotificationBidderAuctionAlmostOverGqlType";
import ActivityNotificationBidderAuctionExtendedGqlType from "src/schema/object/notifications/ActivityNotificationBidderAuctionExtendedGqlType";
import ActivityNotificationBidderAuctionSettledGqlType from "src/schema/object/notifications/ActivityNotificationBidderAuctionSettledGqlType";
import ActivityNotificationBidderClaimPnftGqlType from "src/schema/object/notifications/ActivityNotificationBidderClaimPnftGqlType";
import ActivityNotificationBidderClaimPnftReminderGqlType from "src/schema/object/notifications/ActivityNotificationBidderClaimPnftReminderGqlType";
import ActivityNotificationBidderLostAuctionGqlType from "src/schema/object/notifications/ActivityNotificationBidderLostAuctionGqlType";
import ActivityNotificationBidderOutbidGqlType from "src/schema/object/notifications/ActivityNotificationBidderOutbidGqlType";
import ActivityNotificationBidderWonAuctionGqlType from "src/schema/object/notifications/ActivityNotificationBidderWonAuctionGqlType";
import ActivityNotificationBonkClaimGqlType from "src/schema/object/notifications/ActivityNotificationBonkClaimGqlType";
import ActivityNotificationBuyerOfferAcceptedGqlType from "src/schema/object/notifications/ActivityNotificationBuyerOfferAcceptedGqlType";
import ActivityNotificationBuyerOfferExpiredGqlType from "src/schema/object/notifications/ActivityNotificationBuyerOfferExpiredGqlType";
import ActivityNotificationCampaignAddedAsTeamMemberGqlType from "src/schema/object/notifications/ActivityNotificationCampaignAddedAsTeamMemberGqlType";
import ActivityNotificationCampaignApprovedGqlType from "src/schema/object/notifications/ActivityNotificationCampaignApprovedGqlType";
import ActivityNotificationCampaignCommunityNewUpdateSharedGqlType from "src/schema/object/notifications/ActivityNotificationCampaignCommunityNewUpdateShared";
import ActivityNotificationCampaignFollowersCampaignPublishedGqlType from "src/schema/object/notifications/ActivityNotificationCampaignFollowersCampaignPublishedGqlType";
import ActivityNotificationCampaignGoalReachedXPercentGqlType from "src/schema/object/notifications/ActivityNotificationCampaignGoalReachedXPercentGqlType";
import ActivityNotificationCampaignRejectedGqlType from "src/schema/object/notifications/ActivityNotificationCampaignRejectedGqlType";
import ActivityNotificationCampaignRejectedWithFeedbackGqlType from "src/schema/object/notifications/ActivityNotificationCampaignRejectedWithFeedbackGqlType";
import ActivityNotificationCollabRequestGqlType from "src/schema/object/notifications/ActivityNotificationCollabRequestGqlType";
import ActivityNotificationCreatorSecondarySaleGqlType from "src/schema/object/notifications/ActivityNotificationCreatorSecondarySaleGqlType";
import ActivityNotificationFollowerAuctionAlmostOverGqlType from "src/schema/object/notifications/ActivityNotificationFollowerAuctionAlmostOverGqlType";
import ActivityNotificationFollowerNewEditionsListedGqlType from "src/schema/object/notifications/ActivityNotificationFollowerNewEditionsListedGqlType";
import ActivityNotificationFollowerNewPieceListedGqlType from "src/schema/object/notifications/ActivityNotificationFollowerNewPieceListedGqlType";
import ActivityNotificationFollowerNewPieceListedSecondaryGqlType from "src/schema/object/notifications/ActivityNotificationFollowerNewPieceListedSecondaryGqlType";
import ActivityNotificationFollowerNewPieceScheduledGqlType from "src/schema/object/notifications/ActivityNotificationFollowerNewPieceScheduledGqlType";
import ActivityNotificationFollowerScheduledAuctionIsLiveGqlType from "src/schema/object/notifications/ActivityNotificationFollowerScheduledAuctionIsLiveGqlType";
import ActivityNotificationInvitesConvertedToCreatorGqlType from "src/schema/object/notifications/ActivityNotificationInvitesConvertedToCreatorGqlType";
import ActivityNotificationInvitesInviteeAcceptedInviteGqlType from "src/schema/object/notifications/ActivityNotificationInvitesInviteeAcceptedInviteGqlType";
import ActivityNotificationNewFollowerGqlType from "src/schema/object/notifications/ActivityNotificationNewFollowerGqlType";
import ActivityNotificationOwnerAuctionEndedGqlType from "src/schema/object/notifications/ActivityNotificationOwnerAuctionEndedGqlType";
import ActivityNotificationOwnerAuctionEndedNoBidsGqlType from "src/schema/object/notifications/ActivityNotificationOwnerAuctionEndedNoBidsGqlType";
import ActivityNotificationOwnerAuctionExtendedGqlType from "src/schema/object/notifications/ActivityNotificationOwnerAuctionExtendedGqlType";
import ActivityNotificationOwnerAuctionSettledGqlType from "src/schema/object/notifications/ActivityNotificationOwnerAuctionSettledGqlType";
import ActivityNotificationOwnerEditionSoldGqlType from "src/schema/object/notifications/ActivityNotificationOwnerEditionSoldGqlType";
import ActivityNotificationOwnerEditionsSoldOutGqlType from "src/schema/object/notifications/ActivityNotificationOwnerEditionsSoldOutGqlType";
import ActivityNotificationOwnerFirstBidReceivedGqlType from "src/schema/object/notifications/ActivityNotificationOwnerFirstBidReceivedGqlType";
import ActivityNotificationOwnerGenerativeMintSoldOutGqlType from "src/schema/object/notifications/ActivityNotificationOwnerGenerativeMintSoldOutGqlType";
import ActivityNotificationOwnerOfferReceivedGqlType from "src/schema/object/notifications/ActivityNotificationOwnerOfferReceivedGqlType";
import ActivityNotificationOwnerOtherBidReceivedGqlType from "src/schema/object/notifications/ActivityNotificationOwnerOtherBidReceivedGqlType";
import ActivityNotificationOwnerPieceSoldAsInstantSaleGqlType from "src/schema/object/notifications/ActivityNotificationOwnerPieceSoldAsInstantSaleGqlType";
import ActivityNotificationUnlockableDeclinedToSharedInfoGqlType from "src/schema/object/notifications/ActivityNotificationUnlockableDeclinedToSharedInfoGqlType";
import ActivityNotificationUnlockableInfoSharedGqlType from "src/schema/object/notifications/ActivityNotificationUnlockableInfoSharedGqlType";
import ActivityNotificationUnlockableShareInfoGqlType from "src/schema/object/notifications/ActivityNotificationUnlockableShareInfoGqlType";
import Typename from "src/types/enums/Typename";

const ActivityNotificationGqlType = new GraphQLUnionType({
  name: Typename.ActivityNotification,
  types: [
    ActivityNotificationAirdropCompletedGqlType,
    ActivityNotificationAirdropGiftReceivedGqlType,
    ActivityNotificationBidderAuctionAlmostOverGqlType,
    ActivityNotificationBidderAuctionExtendedGqlType,
    ActivityNotificationBidderAuctionSettledGqlType,
    ActivityNotificationBidderClaimPnftGqlType,
    ActivityNotificationBidderClaimPnftReminderGqlType,
    ActivityNotificationBidderLostAuctionGqlType,
    ActivityNotificationBidderOutbidGqlType,
    ActivityNotificationBidderWonAuctionGqlType,
    ActivityNotificationBonkClaimGqlType,
    ActivityNotificationBuyerOfferAcceptedGqlType,
    ActivityNotificationBuyerOfferExpiredGqlType,
    ActivityNotificationCampaignAddedAsTeamMemberGqlType,
    ActivityNotificationCampaignApprovedGqlType,
    ActivityNotificationCampaignCommunityNewUpdateSharedGqlType,
    ActivityNotificationCampaignFollowersCampaignPublishedGqlType,
    ActivityNotificationCampaignGoalReachedXPercentGqlType,
    ActivityNotificationCampaignRejectedGqlType,
    ActivityNotificationCampaignRejectedWithFeedbackGqlType,
    ActivityNotificationCollabRequestGqlType,
    ActivityNotificationCreatorSecondarySaleGqlType,
    ActivityNotificationFollowerAuctionAlmostOverGqlType,
    ActivityNotificationFollowerNewEditionsListedGqlType,
    ActivityNotificationFollowerNewPieceListedGqlType,
    ActivityNotificationFollowerNewPieceListedSecondaryGqlType,
    ActivityNotificationFollowerNewPieceScheduledGqlType,
    ActivityNotificationFollowerScheduledAuctionIsLiveGqlType,
    ActivityNotificationInvitesConvertedToCreatorGqlType,
    ActivityNotificationInvitesInviteeAcceptedInviteGqlType,
    ActivityNotificationNewFollowerGqlType,
    ActivityNotificationOwnerAuctionEndedGqlType,
    ActivityNotificationOwnerAuctionEndedNoBidsGqlType,
    ActivityNotificationOwnerAuctionExtendedGqlType,
    ActivityNotificationOwnerAuctionSettledGqlType,
    ActivityNotificationOwnerEditionSoldGqlType,
    ActivityNotificationOwnerEditionsSoldOutGqlType,
    ActivityNotificationOwnerFirstBidReceivedGqlType,
    ActivityNotificationOwnerGenerativeMintSoldOutGqlType,
    ActivityNotificationOwnerOfferReceivedGqlType,
    ActivityNotificationOwnerOtherBidReceivedGqlType,
    ActivityNotificationOwnerPieceSoldAsInstantSaleGqlType,
    ActivityNotificationUnlockableDeclinedToSharedInfoGqlType,
    ActivityNotificationUnlockableInfoSharedGqlType,
    ActivityNotificationUnlockableShareInfoGqlType,
  ],
});

export default ActivityNotificationGqlType;
