-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.username_length_fn(user_row "User")
--  RETURNS int
--  LANGUAGE sql
--  STABLE
-- AS $function$
--   SELECT LENGTH(username)
--   FROM "User"
--   WHERE id = user_row.id
-- $function$;
