-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Asset" add column "premintPreviewAssetCandyMachineId" uuid
--  null;
