-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."UnlockableWinner" add column "hasCreatorDismissedSeeInfoCta" boolean
--  not null default 'false';
