-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Post" add column "visibility" text
--  not null default 'Public';
