-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Poll" add column "isMultiSelect" boolean
--  not null default 'true';
