-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Nft" add column "timeExtensionDurationInSeconds" integer
--  not null default '900';
