-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."Request" add column "timeCreated" timestamptz
--  not null default now();
