-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."NftTransaction" add column "ixInnerIndex" integer
--  not null default '-1';
