-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."NftToCollaborator" add column "requestId" uuid
--  not null unique;
