-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."User" add column "shouldSeeDiscordOnboardingPrompt" Boolean
--  not null default 'true';
